apps:
  - namespace: taxi
    enabled: true
    app: taxi-app
    image: 201685886146.dkr.ecr.eu-central-1.amazonaws.com/laravel-app:TAG
    replicas: 13
    minReplicas: 13
    maxReplicas: 150
    domain: dev.admin.taxi.com.sa
    storage:
      enabled: true
      size: 21Gi
      storageClassName: efs-sc
    images:
      size: 21Gi
      storageClassName: efs-sc
    tripfiles:
      size: 21Gi
      storageClassName: efs-sc
    limits:
      cpu: "1700m"
      memory: "10Gi"
    requests:
      cpu: "1300m"
      memory: "3Gi"
