apiVersion: v1
kind: Pod
metadata:
  name: inspection-pod
  namespace: taxi
spec:
  containers:
  - name: inspection-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
          runAsUser: 1000
          runAsGroup: 1000
    volumeMounts:
    - name: storage
      mountPath: /var/www/html/public/images
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: taxi-app-images-pvc